# Generated by Django 6.0 on 2025-12-03 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('idade', models.PositiveIntegerField()),
                ('raça', models.CharField(max_length=40)),
                ('especieAnimal', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animais',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Dono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=11)),
                ('endereco', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Adocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_Adocao', models.DateField(auto_now_add=True)),
                ('Animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cadastros.animal')),
                ('Dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cadastros.dono')),
            ],
            options={
                'verbose_name': 'Adoção',
                'verbose_name_plural': 'Adoções',
                'ordering': ['-id'],
            },
        ),
    ]
